version: '2'
services:
#Building shard replica set 1
  mongo_rs1_n1:
    container_name: mongo_rs1_n1
    image: mongo
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017
    ports:
      - 40117:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_rs1_n1:/data/db
  mongo_rs1_n2:
    container_name: mongo_rs1_n2
    image: mongo
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017
    ports:
      - 40127:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_rs1_n2:/data/db
  mongo_rs1_n3:
    container_name: mongo_rs1_n3
    image: mongo
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017
    ports:
      - 40137:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_rs1_n3:/data/db
#Building shard replica set 2
  mongo_rs2_n1:
    container_name: mongo_rs2_n1
    image: mongo
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 40217:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_rs2_n1:/data/db
  mongo_rs2_n2:
    container_name: mongo_rs2_n2
    image: mongo
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 40227:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_rs2_n2:/data/db
  mongo_rs2_n3:
    container_name: mongo_rs2_n3
    image: mongo
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 40237:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_rs2_n3:/data/db



volumes:
  mongo_rs1_n1: {}
  mongo_rs1_n2: {}
  mongo_rs1_n3: {}
  mongo_rs2_n1: {}
  mongo_rs2_n2: {}
  mongo_rs2_n3: {}