version: '2'
services:
#Building shard router instances
  mongo_shard1:
    container_name: mongo_shard1
    image: mongo
    command: mongos --configdb mongo_rs1_conf/mongo_cfg1:27017,mongo_cfg2:27017,mongo_cfg3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mongo_shard2:
    container_name: mongo_shard2
    image: mongo
    command: mongos --configdb mongo_rs1_conf/mongo_cfg1:27017,mongo_cfg2:27017,mongo_cfg3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro